const images = {
  background1: require('../assets/images/background1.png'),
  background2: require('../assets/images/background2.png'),
  logo: require('../assets/images/logo.png'),
  username: require('../assets/images/username.png'),
  password: require('../assets/images/password.png'),
  email: require('../assets/images/email.png'),
  phone: require('../assets/images/phone.png'),
  backArrow: require('../assets/images/back_arrow.png'),
  fail: require('../assets/images/fail.png'),
  success: require('../assets/images/success.png'),
  // Tab Button Icons
  homeActive: require('../assets/images/home_active.png'),
  homeInactive: require('../assets/images/home_inactive.png'),
  shopingActive: require('../assets/images/shoping_active.png'),
  shopingInactive: require('../assets/images/shoping_inactive.png'),
  reportActive: require('../assets/images/report_active.png'),
  reportInactive: require('../assets/images/report_inactive.png'),
  promotionActive: require('../assets/images/promotion_active.png'),
  promotionInactive: require('../assets/images/promotion_inactive.png'),
  // Side Menu Icons
  close: require('../assets/images/close.png'),
  menuProfile: require('../assets/images/menu_profile.png'),
  menuFAQ: require('../assets/images/menu_faq.png'),
  menuAbout: require('../assets/images/menu_about.png'),
  menuContact: require('../assets/images/menu_contact.png'),
  menuLogout: require('../assets/images/menu_logout.png'),
  // Header Icons
  back: require('../assets/images/back.png'),
  menu: require('../assets/images/menu.png'),
  // Profile Page Icons
  profileCamera: require('../assets/images/profile_camera.png'),
  profileUser: require('../assets/images/profile_user.png'),
  profileMail: require('../assets/images/profile_mail.png'),
  profileMap: require('../assets/images/profile_map.png'),
  profilePassword: require('../assets/images/profile_password.png'),
  buttonBG1: require('../assets/images/button_bg1.png'),
  // FAQ Page Icons
  forward: require('../assets/images/forward.png'),
  // Contact Page Icons
  contactPhone: require('../assets/images/contact_phone.png'),
  contactEmail: require('../assets/images/contact_email.png'),
  // Home Tab Page Images
  homeBuyCredit: require('../assets/images/home_buy_credit.png'),
  homePayCard: require('../assets/images/home_pay_card.png'),
  photoPlaceholder: require('../assets/images/profile.png'),
  buttonBG2: require('../assets/images/button_bg2.png'),
  homeMobile: require('../assets/images/home_mobile.png'),
  homePostpaid: require('../assets/images/home_postpaid.png'),
  homeUtilities: require('../assets/images/home_utilities.png'),
  homeInternational: require('../assets/images/home_international.png'),
  homeEtransfer: require('../assets/images/home_etransfer.png'),
  homeAbout: require('../assets/images/home_about.png'),
  buycreditJomPay: require('../assets/images/buycredit_jompay.png'),
  buycreditCreditCard: require('../assets/images/buycredit_creditcard.png'),
  buycreditManual: require('../assets/images/buycredit_manual.png'),
  jompayRoundRect: require('../assets/images/jompay_roundrect.png'),
  pickerIconDate: require('../assets/images/pickerIconDate.png'),
  pickerIconTime: require('../assets/images/pickerIconTime.png'),
  cardIcon: require('../assets/images/card_icon.png'),
  userIcon: require('../assets/images/user_icon.png'),
  buttonBG4: require('../assets/images/button_bg4.png'),
  imagePlaceholder: require('../assets/images/image_placeholder.png'),
  creditTransferContactIcon: require('../assets/images/credit_transfer_contact.png'),
  secureIcon: require('../assets/images/secure_icon.png'),
  cardHackerSafe: require('../assets/images/card_hackersafe.png'),
  cardMaster: require('../assets/images/card_master.png'),
  cardPCIDSS: require('../assets/images/card_pcidss.png'),
  cardVisa: require('../assets/images/card_visa.png'),
  importantIcon: require('../assets/images/important_icon.png'),
  banner1: require('../assets/images/banner1.png'),
  banner2: require('../assets/images/banner2.png'),
  banner3: require('../assets/images/banner3.png'),
  // Shoping Tab Page Images
  categorySearch: require('../assets/images/category_search.png'),
  categoryLove: require('../assets/images/category_love.png'),
  categoryCart: require('../assets/images/category_cart.png'),
  categorySort: require('../assets/images/category_sort.png'),
  categoryView: require('../assets/images/category_view.png'),
  categoryFilter: require('../assets/images/category_filter.png'),
  // Report Tab Page Images
  buttonBG3: require('../assets/images/button_bg3.png'),
  reportBuyCredits: require('../assets/images/report_buycredits.png'),
  reportRebates: require('../assets/images/report_rebates.png'),
  reportTransaction: require('../assets/images/report_transaction.png'),
  reportTransferIn: require('../assets/images/report_transferin.png'),
  reportTransferOut: require('../assets/images/report_transferout.png'),
  digiIcon: require('../assets/images/digi.png'),
  // Promotion Tab Tage Images
  testPromotion1: require('../assets/images/promotion_1.png'),
  testPromotion2: require('../assets/images/promotion_2.png'),
  testPromotion3: require('../assets/images/promotion_3.png'),
  testPromotion4: require('../assets/images/promotion_4.png'),
  testPromotion5: require('../assets/images/promotion_5.png'),
  testPromotion6: require('../assets/images/promotion_6.png'),
  locationIcon: require('../assets/images/location_icon.png'),
  timeIcon: require('../assets/images/time_icon.png'),
  tncIcon: require('../assets/images/tnc_icon.png'),
};

export default images;