export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const SET_DOMESTIC_PRODUCTS = 'SET_DOMESTIC_PRODUCTS';
export const SET_INTERNATIONAL_PRODUCTS = 'SET_INTERNATIONAL_PRODUCTS';
export const SET_UTILITY_PRODUCTS = 'SET_UTILITY_PRODUCTS';
export const SET_POSTPAID_PRODUCTS = 'SET_POSTPAID_PRODUCTS';